DROP TABLE PROJETS;
DROP TABLE PARTICIPANTS_PROJETS;
DROP TABLE LOGICIELS;
DROP TABLE MATERIELS;
DROP TABLE TICKETS;
DROP TABLE UTILISATEURS;

DROP TABLESPACE stockageCergy INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE stockagePau INCLUDING CONTENTS AND DATAFILES;

DROP ROLE super_admin;
DROP ROLE admin;

DROP USER Cergy CASCADE;
DROP USER Pau CASCADE ;



