CREATE OR REPLACE VIEW Noms_Utilisateurs AS
  SELECT PRENOM, NOM
  FROM UTILISATEURS;

CREATE OR REPLACE VIEW Noms_Participants_Projets AS
    SELECT PROJETS.NOM, UTILISATEURS.PRENOM
    FROM UTILISATEURS
    INNER JOIN PARTICIPANTS_PROJETS PP on UTILISATEURS.ID = PP.UTILISATEUR_ID
    INNER JOIN PROJETS on PP.PROJET_ID = PROJETS.ID;

CREATE OR REPLACE VIEW Nombre_De_Projets AS
    SELECT UTILISATEURS.PRENOM, COUNT(PROJETS.NOM) AS NOMBRE_DE_PROJETS
    FROM UTILISATEURS
    INNER JOIN PARTICIPANTS_PROJETS PP on UTILISATEURS.ID = PP.UTILISATEUR_ID
    INNER JOIN PROJETS on PP.PROJET_ID = PROJETS.ID
    GROUP BY UTILISATEURS.PRENOM;


-- LIGNE DE DROIT D'EXECUTUION DE CERTAINE vue POUR PAU
-- GRANT EXECUTE ON nom_vue TO admin;